import type { Role } from "./types";

export const roles: Role[] = [
  { id: "umbral-guard", name: "Guardia del Umbral", description: "Protectora de caminos malditos, pasos de montaña y duelos bajo juramento.", mainStat: "courage", secondaryStat: "body", specialAbility: "Guardia Firme: reduce una consecuencia de combate, trampa o persecución.", limitation: "Tiende a interponerse aunque no sea prudente.", playstyle: "Abrir paso y proteger." },
  { id: "soul-oracle", name: "Oráculo de Almas", description: "Interpreta fantasmas, reliquias vivas y pactos que nadie debió firmar.", mainStat: "focus", secondaryStat: "mind", specialAbility: "Lectura de Alma: identifica si una pista viene de fantasma, dragón o maldición.", limitation: "Las almas también miran de vuelta.", playstyle: "Investigar lo sobrenatural." },
  { id: "ruin-locksmith", name: "Cerrajera de Ruinas", description: "Sobrevive a cerraduras, venenos, mapas falsos y salones traicioneros.", mainStat: "luck", secondaryStat: "creativity", specialAbility: "Mano Rápida: convierte una falla en una salida parcial una vez por escena.", limitation: "Nunca confía gratis.", playstyle: "Explorar y desactivar peligros." },
  { id: "ash-oath", name: "Juramentado de Ceniza", description: "Porta un voto antiguo que los muertos reconocen.", mainStat: "body", secondaryStat: "courage", specialAbility: "Voto Firme: no retrocede cuando el peligro sube.", limitation: "Romper promesas le cuesta energía.", playstyle: "Resistir y negociar con muertos." },
  { id: "blood-diplomat", name: "Diplomática de Sangre", description: "Experta en romances secretos, traiciones nobles y palabras peligrosas.", mainStat: "charm", secondaryStat: "mind", specialAbility: "Verdad Incómoda: hace una pregunta directa a un PNJ hostil.", limitation: "Las emociones pueden complicar el objetivo.", playstyle: "Persuadir y leer vínculos." },
  { id: "relic-binder", name: "Vinculador de Reliquias", description: "Aventurera unida a una mascota legendaria y a magia de tesoros antiguos.", mainStat: "creativity", secondaryStat: "focus", specialAbility: "Lazo Legendario: activa mascota con +1d4 si encaja con la escena.", limitation: "La reliquia o mascota también tiene voluntad.", playstyle: "Soluciones raras con compañero." },
  { id: "guild-shadow", name: "Sombra del Gremio", description: "Ladrona criada entre tejados: dagas gemelas, ganzúas de hueso, bolsillos ajenos y salidas que nadie más ve.", mainStat: "focus", secondaryStat: "luck", specialAbility: "Dagas Gemelas: si el primer golpe falla, el segundo convierte la falla en éxito parcial (1 vez por combate). Ganzúas de hueso: las cerraduras comunes se abren sin tirar dados.", limitation: "Lo que brilla se le pega a los dedos, aunque sea del aliado equivocado.", playstyle: "Infiltrarse, robar y desaparecer." },
  { id: "dawn-archer", name: "Arquera del Alba", description: "Porta un arco encantado que susurra hacia dónde mira el peligro; sus flechas recuerdan a quién tocaron.", mainStat: "mind", secondaryStat: "focus", specialAbility: "Arco del Alba: una flecha encantada por escena alcanza o revela lo que el ojo no ve (un objetivo oculto, una cuerda, una mentira).", limitation: "El arco elige cuándo cantar: en la oscuridad total guarda silencio.", playstyle: "Precisión, distancia y verdad revelada." }
];
