import type { Species } from "./types";

export const species: Species[] = [
  { id: "human-oath", name: "Humano de Juramento", description: "Linaje de aldeas, casas nobles y pactos antiguos.", statBonus: { courage: 1 }, passiveTrait: "Cuando da su palabra, los PNJ dudan antes de traicionarla.", visualFlavor: "capa de viaje, espada gastada, sello familiar", quirk: "Le cuesta abandonar una promesa incluso si es peligrosa." },
  { id: "duskelder", name: "Elfo del Velo", description: "Habitante de bosques rojos, cortes secretas y ruinas con memoria.", statBonus: { focus: 1 }, passiveTrait: "Percibe rastros de ilusión, presencias feéricas y magia antigua.", visualFlavor: "ojos plateados, marcas de luna, ropa de corte sombría", quirk: "Habla con demasiada calma cuando algo le duele." },
  { id: "rune-dwarf", name: "Enano de Runafosa", description: "Pueblo de minas santas, fortalezas caídas y mapas grabados en piedra.", statBonus: { body: 1 }, passiveTrait: "Resiste derrumbes, trampas mecánicas y presión física.", visualFlavor: "barba trenzada, martillo ritual, runas en los nudillos", quirk: "Nunca confía en una puerta demasiado limpia." },
  { id: "road-halfling", name: "Mediano del Camino", description: "Gente de caravanas, tabernas, secretos pequeños y escapes imposibles.", statBonus: { luck: 1 }, passiveTrait: "Una vez por escena encuentra una salida, escondite o contacto menor.", visualFlavor: "botas de viaje, amuletos robados, sonrisa rápida", quirk: "Promete que fue casualidad aunque no lo haya sido." },
  { id: "dragon-marked", name: "Marcado por Dragón", description: "Descendiente o elegido por un alma dracónica dormida.", statBonus: { creativity: 1 }, passiveTrait: "El fuego, los tesoros y los juramentos dracónicos reaccionan a su presencia.", visualFlavor: "escamas sutiles, iris dorado, cicatriz luminosa", quirk: "Siente codicia por reliquias que no entiende." },
  { id: "grave-touched", name: "Tocado por la Tumba", description: "Alguien que murió un instante y volvió con ecos del otro lado.", statBonus: { mind: 1 }, passiveTrait: "Puede notar cuando un fantasma, zombi o maldición altera una escena.", visualFlavor: "piel fría, rosario roto, sombra que tarda en moverse", quirk: "Recuerda fragmentos de funerales ajenos." }
];
